
theme: jekyll-theme-minimal
title: Aprilia Evans' Homepage
description: Aprilia Evans is a dedicated and results-oriented Data Analyst and an ex banker with broad knowledge in Banking and Financial industry. 
She has a passion for translating complex data into actionable insights. 
Her journey in the world of data began with a fascination for numbers and a desire to uncover hidden patterns that drive decision-making. 
She always honed her skills in data analysis, visualization, and interpretation, helping organizations make informed choices and optimize their strategies.
